### ISSUE TITLE
Libcmis fails cppcheck-test

### ISSUE THREAD

**Issue by PPed72** [tdf/libcmis#12]
Since upgrading to version 1.72 of cppcheck, the cppcheck test fails:

FAIL: cppcheck-test.sh
======================

[src/libcmis/oauth2-providers.cxx:163]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[src/libcmis/oauth2-providers.cxx:167]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[src/libcmis/oauth2-providers.cxx:169]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[src/libcmis/ws-relatedmultipart.cxx:125]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[src/libcmis/ws-relatedmultipart.cxx:146]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[src/libcmis/ws-relatedmultipart.cxx:203]: (performance) Inefficient usage of string::find() in condition; string::compare() would be faster.
[*]: (information) Unmatched suppression: noExplicitCopyMoveConstructor
(information) Cppcheck cannot find all the include files (use --check-config for details)
FAIL cppcheck-test.sh (exit status: 1)

Last known working cppcheck version was 1.69. I've tried with all versions of cppcheck from 1.72 to 1.75 and with git master and they do not work.

See relevant Gentoo bug: https://bugs.gentoo.org/show_bug.cgi?id=577926

**Comment by dtardon** [comment]
There's no problem with cppcheck: it does work as expected. It's just that newer versions find more stuff than the older ones; because we pass --error-exitcode=1, cppcheck exits with non-zero exitcode if any issue is found, which is interpreted as a failure by autotest. I've disabled the information checks, which don't make much sense for general use, but there is still enough legitimate issues.

Another question, of course, is why gentoo uses cppcheck. It's a development tool, not much suited for use by distributions...

**Comment by thesamesam** [comment]
FTR, I think the issue was that it was automagically using cppcheck if installed, not us intentionally enabling it in our packaging.

But should be obsolete with 0.5.2 anyway:
> 0.5.2
>
> [...]
>  * Dropped cppcheck run from "make check". A new "make cppcheck" target
>    was created for it

(Just commenting here as I came across it when digging into why we weren't running tests still.)
